### ISSUE TITLE
Add opt-in flag to convert `tslint:disable` comments to `eslint-disable`

### ISSUE THREAD

**Issue by JoshuaKGoldberg** [typescript-eslint/tslint-to-eslint-config#136]
### 🚀 Feature Request

Per a comment in https://github.com/sourcegraph/sourcegraph/pull/5072 - it'd be swell to automate that process as well. `tslint-to-eslint-config` already has data from rule mergers, so when the config is generated, mapping through `tslint-disable` comments can use the same information generated by them.

#### Existing Behavior

Nothing happens.

#### Change Proposal

Add an optional CLI flag that takes in a glob or globs of source files to convert, and changes `tslint:disable-next-line: no-floating-promises` to the equivalent `eslint-disable-next-line: @typescript-eslint/no-floating-promises` lines.

**Comment by KingDarBoja** [comment]
@JoshuaKGoldberg I think I have a basic setup but not sure how to test it without relying on making a separate test file since I am not confident if it gonna work. You can check out [this branch](https://github.com/KingDarBoja/tslint-to-eslint-config/tree/feature/opt-in-flag-convert-disable-comments) what I have done so far.

**Comment by JoshuaKGoldberg** [comment]
@KingDarBoja That looks like a great start. Now that you mention it, it does seem like a `ts.createSourceFile` inside is the only way to know what's a real disable comment... fun. 😅 

For testing it, a good start might be to try splitting `convertComments` into >=3 files:
* Exported function that creates a `ts.SourceFile` for a given file - either including the file system shenanigans, or with that split up into a separate files
* Exported function that finds all matching comments in a source file
* Exported function that, given a regexp comment match, finds the equivalent ESLint rule name for it

YMMV. 🚗

Btw, maybe `--convertComments` for the CLI flag?

**Comment by KingDarBoja** [comment]
@JoshuaKGoldberg Don't worry, I made it from the current source code by calling the `node ../tslint-to-eslint-config/bin/tslint-to-eslint-config -c` command on some test folder and so far, I am getting the comments but still dealing with the `for` loop logic.

I will push new changes in few minutes, ahd to fix the regex pattern and the source dirname, in the meantime, look at the output:
![testing convert comments](https://user-images.githubusercontent.com/30560560/67165710-2c6f4880-f34e-11e9-9ba0-6017ea7d0fe3.png)

I am properly extracting the source file regex match and I do have some information of where the comments are located. Just as extra info, my test file is a copy-paste of the `convertComments` code with some `tslint` comments 😆

**Comment by JoshuaKGoldberg** [comment]
_it's so beautiful_

**Comment by KingDarBoja** [comment]
> _it's so beautiful_

I fixed already the regex pattern, at the end, had to play a little with it because I am not so skilled with it. Now we get the proper `for-loop` check and we can do whatever we want inside it.

Now the next thing would be the rule change logic and overwriting the file with the proper path (which looks like it is not being taken into account).

Cheers!

**Comment by JoshuaKGoldberg** [comment]
Oh hey I just stumbled upon https://github.com/sunnyone/tslint-comment-to-eslint. That's a really nifty package, and really impressive in its brevity. :100:

FYI @sunnyone!
