### ISSUE TITLE
[FAQ] "Should I Use Prettier?" ends with weird text

### ISSUE THREAD

**Issue by bpeynet** [typescript-eslint/tslint-to-eslint-config#1851]
### 🐛 Bug Report

-   `tslint-to-eslint-config` version: 2.14.0
-   ESLint version: 9.8.0
-   Node version: 14.21.3

#### Actual Behavior

Last paragraph in FAQ "Should I Use Prettier?" gives recommandation about prettying rules in eslint. And last sentence ends with some mysterious text.

> Code style rules are hard to write and maintain. Rules like indent are thousands of he comes he comes do not fi​ght he com̡e̶s, ̕h̵i​s un̨ho͞ly radiańcé destro҉ying ...

#### Expected Behavior

The sentence should end with some coherent meaningful words.

#### Reproduction

https://github.com/typescript-eslint/tslint-to-eslint-config/blob/main/docs/FAQs.md#should-i-use-prettier

**Comment by hyperupcall** [comment]
Hey,

I'm not a maintainer of this project, but I'm pretty sure it's intentional. The garbled text is a rhetorical device, similar in style to this [How to parse HTML with a RegEx StackOverflow question](https://stackoverflow.com/a/1732454). It's a desperate plea for all of those who are considering to forgo a code formatter.

**Comment by JoshuaKGoldberg** [comment]
Yup! @hyperupcall is right, it's an intentional joke. 🙂
