### ISSUE TITLE
Cannot find module '../creation/pruning/removeExtendsDuplicatedRules'

### ISSUE THREAD

**Issue by RLashofRegas** [typescript-eslint/tslint-to-eslint-config#572]
### 🐛 Bug Report

-   `tslint-to-eslint-config` version: 1.0.0-beta1
-   ESLint version: 7.0.0
-   Node version: 14.2.0

#### Actual Behavior

When I run `npx tslint-to-eslint-config` I get the following output:
```
Cannot find module '../creation/pruning/removeExtendsDuplicatedRules'
Require stack:
- /home/rlashof/.npm/_npx/14458/lib/node_modules/tslint-to-eslint-config/src/cli/main.js
- /home/rlashof/.npm/_npx/14458/lib/node_modules/tslint-to-eslint-config/bin/tslint-to-eslint-config
```

When I install the package manually with `npm install tslint-to-eslint-config` and then go look at the src it looks like the filename is incorrect, I see this (notice capital U "DUplicates): `removeExtendsDUplicatedRules.js`

#### Expected Behavior

running `npx tslint-to-eslint-config` works without errors

#### Reproduction

https://github.com/RLashofRegas/RobinLashofRegas.com/tree/upgrade-angular-again

**Comment by RLashofRegas** [comment]
FYI when I execute `npx tslint-to-eslint-config@1.0.0-beta` it seems to work so definitely an issue with the latest version released yesterday

**Comment by JoshuaKGoldberg** [comment]
Grr. This is what I get for publishing from a Windows machine instead of fixing #392. Thanks for reporting @RLashofRegas!

`tslint-to-eslint-config@1.0.0-beta2` is now [published](https://www.npmjs.com/package/tslint-to-eslint-config/v/1.0.0-beta2) and should fix this issue. 

Closing this issue as I think it's resolved, but please do comment back here or open a new one if any other problems pop up!
