### ISSUE TITLE
Use ESLint's existing config lookup system to look up ESLint config

### ISSUE THREAD

**Issue by JoshuaKGoldberg** [typescript-eslint/tslint-to-eslint-config#58]
### 🚀 Feature Request

Right now, if you don't specify an `--eslint` to an ESLint configuration file, only `.eslintrc.js` will be looked at. ESLint allows other formats such as JSON and YAML.

#### Existing Behavior

The path to look up an existing ESLint configuration file is hardcoded to `.eslintrc.js`.

#### Change Proposal

Use whatever ESLint does (or, if that's not easily doable, some similar semblance) to look up that file path.

Related: #10

**Comment by JoshuaKGoldberg** [comment]
In retrospect, this seems lower priority. Folks can manually pass their ESLint file path.

The investigation in #232 is a cool one but let's hold off on accepting PRs till a solution that doesn't involve `rewire` or `__get__` is known. 😄

**Comment by jeremyyap** [comment]
@JoshuaKGoldberg here's what I found while looking into #232.

It turns out the argument passed to `--print-config` is not the ESLint config file path, but instead the code file you want to print the effective configuration for. This is necessary due to ESLint's configuration cascading whereby different files may have different rulesets.

Since we only care about the root ESLint config file, we can pass in a file that should exist in the root folder of every project and ESLint will resolve the config file path by itself:

```sh
eslint --print-config package-lock.json
```

And if we want to specify a custom config file:

```sh
eslint --print-config package-lock.json --config <eslintrc file>
```

Finally, here is a possible method to get the **reported** configuration using ESLint's API

```js
import { CLIEngine } from "eslint";
...
return new CLIEngine({}).getConfigForFile("package-lock.json");
```

**Comment by JoshuaKGoldberg** [comment]
Yeah, I poked around here and couldn't find a good way to extract the internal ESLint logic within the config factory. The point of this issue was that it would be good to detect any of the support ESLint configuration names; I'll file a separate issue to do specifically that manually.
