### ISSUE TITLE
Add a flag to disable computing full configurations

### ISSUE THREAD

**Issue by JoshuaKGoldberg** [typescript-eslint/tslint-to-eslint-config#746]
### 🚀 Feature Request

Some configurations, particularly those for monorepos, don't need to compute the full/extended config for a conversion. Their configurations might exist solely to modify a few choice rules from an extended shared config.

```json
{
  "extends": "@org/eslint-config",
  "rules" {
    "specific-rule": "error"
  }
}
```

#### Existing Behavior

There's no way to change the behavior of rule conversions to ignore extended configurations.

#### Change Proposal

How about a `--standalone` flag / `standalone` Node API (once #732 is resolved) to disable fetching and computing the `--print-config` and `extends` rules for lint configurations? Is there a better name for the flag?

In the above example, instead of factoring in `@org/eslint-config`, we'd only look at `rules` -> `specific-rule`.

**Comment by JoshuaKGoldberg** [comment]
@JamesHenry it'd be good, too, to know if this should change how the lint configurations for workspaces are printed out. E.g. should we skip adding in _any_ `"extends"`, `"plugins"`, etc. metadata other than `"rules"`?

**Comment by JamesHenry** [comment]
Hmm yeah I guess in my monorepo use-case a nested project/package config could extend other unique things that you _would_ want to take into account...

So maybe rather than a flag, what we what is to be able to specify particular paths within extends that should be ignored for a particular config. The outer tooling can figure out the path to the root config and instruct the library to ignore any extends references to that?

I don’t think skipping plugins etc would be part of my use-case, we would want to always consider those

**Comment by JoshuaKGoldberg** [comment]
Super interesting. Are there any example workspaces/configs you could post as examples @JamesHenry?

**Comment by JamesHenry** [comment]
Great to catch up with you today - as briefly mentioned on slack after our call, I think I personally no longer need this in light of the changes we discussed to the available Node APIs - I will be able to customize the extends however I need to before ever passing it to the library!

**Comment by JoshuaKGoldberg** [comment]
If anybody is still interested in this, comment below and we can re-open!
