### ISSUE TITLE
Unclear error message when tslint.json doesn't exist

### ISSUE THREAD

**Issue by kumaresan-subramani** [typescript-eslint/tslint-to-eslint-config#823]
🐛 Bug Report

-   `tslint-to-eslint-config` version: X.X.X
-   ESLint version: 7.13.0
-   Node version: 8.11.3

When i run these commands one by one, i am facing below issue

Docs - https://eslint.org/docs/user-guide/getting-started#installation-and-usage

![image](https://user-images.githubusercontent.com/36756050/98530082-7a7e2380-22a4-11eb-8790-f842ed8c65ef.png)

**Comment by kumaresan-subramani** [comment]
when i try below command, throws below error

![image](https://user-images.githubusercontent.com/36756050/98543504-9a1f4700-22b8-11eb-991f-198763606a95.png)

**Comment by kumaresan-subramani** [comment]
**Documentations are not clear, i have tried below listed doc - nothing works**

-  https://eslint.org/docs/user-guide/getting-started#installation-and-usage

-  https://code.visualstudio.com/api/advanced-topics/tslint-eslint-migration

-  https://github.com/typescript-eslint/tslint-to-eslint-config#usage

**Comment by kumaresan-subramani** [comment]
my appplicatoin - https://github.com/kumaresan-subramani/ESlint-tester 


please share steps to switch from TS-lint to Es-lint

**Comment by JoshuaKGoldberg** [comment]
Hi @kumaresan-subramani! Per this repository's README, tslint-to-eslint-config requires Node >=10. You're running Node 8. Please update your version of Node. Given that both `npx eslint --init` and `npx tslint-to-eslint-config` are giving you the same `Path must be a string. Received undefined` error, I doubt the issues you're facing are unique to tslint-to-eslint-config.

Closing this issue for housekeeping, but if you update to Node >=10 (I recommend the latest versions, 14 or 15), and the issue persists, please do feel free to post here again and we can take another look. Thanks!

**Comment by kumaresan-subramani** [comment]
HI @JoshuaKGoldberg ,

Same issue after upgrading node version too.

![image](https://user-images.githubusercontent.com/36756050/98657825-4e2bdb00-2368-11eb-8937-bfdc0c95bfda.png)


## Can you please proper docs to switch tslit to eslit

**Comment by kumaresan-subramani** [comment]
HI @JoshuaKGoldberg ,

## Replication steps

- clone below sample
https://github.com/kumaresan-subramani/ESlint-tester

- give npm install or yarn install

- then follow any one of below docs

1. https://eslint.org/docs/user-guide/getting-started#installation-and-usage

2. https://code.visualstudio.com/api/advanced-topics/tslint-eslint-migration

3. https://github.com/typescript-eslint/tslint-to-eslint-config#usage

**Comment by KingDarBoja** [comment]
The main issue I see is the lack of `tslint.json` file on the repository, which is required to perform the migration to ESLint 🧐

**Comment by kumaresan-subramani** [comment]
Hi @KingDarBoja , thank for reply.

that will refer from here

https://github.com/kumaresan-subramani/ESlint-tester/blob/main/gulpfile.js#L1

i have `tslint.json` file in `@syncfusion/ej2-build-check` package. i have also tried creating `tslint.json` file in root but same issue

**Comment by JoshuaKGoldberg** [comment]
> https://github.com/kumaresan-subramani/ESlint-tester/blob/main/gulpfile.js#L1

Yup, there's your issue! `tslint-to-eslint-config` requires an actual `tslint.json` file to exist on disk. It won't try to parse through Gulp configurations or whatnot.

I can reproduce the latest error you posted as-is in the repository after running `npx tslint-to-eslint-config`. When I add a `tslint.json` file, it starts to works. Let's consider this issue to be tracking improving that error message to be explicit about the requested TSLint file (in this case, the default `tslint.json`) not existing.

FWIW not having a `tslint.json` exist is a very unusual thing. For both ESLint and TSLint, you need a configuration file on disk under a name known to the linter so editor extensions can read it.

**Comment by kumaresan-subramani** [comment]
> i have `tslint.json` file in `@syncfusion/ej2-build-check` package. i have also tried creating `tslint.json` file in root but same issue

Hi @JoshuaKGoldberg ,

I have also tried to add `tslint.json` file in root and tried still same issue

**Comment by kumaresan-subramani** [comment]
@JoshuaKGoldberg ,

FYI

https://github.com/kumaresan-subramani/ESlint-tester/blob/main/tslint.json

i have added that now but still same issue

**Comment by kumaresan-subramani** [comment]
@JoshuaKGoldberg , any update on this

**Comment by JoshuaKGoldberg** [comment]
Hey again @kumaresan-subramani -- I've sent a PR (#827) to improve the error message for when the `tslint.json` file doesn't exist, but otherwise no, not since you posted yesterday that the issue is still happening.

It's great that you're excited to switch from TSLint to ESLint, so if this issue that appears to be only happening for your specific repository is blocking your switch, I'd encourage you to take a look at debugging through `tslint-to-eslint-config` locally. You can take a look at our development docs here: https://github.com/typescript-eslint/tslint-to-eslint-config/blob/main/docs/Development.md. If that's a bit too high intensity for what you're able to spend time on now, you could try putting some `console.log` calls through the `tslint-to-eslint-config` path in your `node_modules/`.

We should also note that `tslint-to-eslint-config` is a purely volunteer project. Two maintainers (myself and KingDarBoja) do this in our spare time because we enjoy the work and like the idea of helping folks move from TSLint to ESLint. As with most open source projects, daily updates are asking more from us than we can put in now. You're more likely to get better responses if you ask for updates in weeks rather than days... and even better responses if you take the time yourself to debug through and fix the issue. :wink:

**Comment by kumaresan-subramani** [comment]
i found my issue

- [ ] https://github.com/typescript-eslint/tslint-to-eslint-config#usage


i have tslint version at 4.0.2
when i upgrade latest it wokrs fine

**Comment by kumaresan-subramani** [comment]
i found my issue

https://github.com/typescript-eslint/tslint-to-eslint-config#usage

i have tslint version at 4.0.2

when i upgrade latest it wokrs fine
