### ISSUE TITLE
Missing tslint rule: number-literal-format

### ISSUE THREAD

**Issue by Kydyralin** [typescript-eslint/tslint-to-eslint-config#825]
### 💥 Missing Converter

-   `tslint-to-eslint-config` version: 2.0.0-beta5
-   `typescript-eslint` version: 4.7.0

#### TSLint Rule Name

number-literal-format

#### Package Source

TSLint rule: [https://palantir.github.io/tslint/rules/number-literal-format/](https://palantir.github.io/tslint/rules/number-literal-format/)

**Comment by Kydyralin** [comment]
I've tried to google for some alternative on ESLint but unfortunately didn't find any. Not sure how many people relies on this rule but since there is still no converter issue for this I've decided to create one.

**Comment by JoshuaKGoldberg** [comment]
Thanks for filing @kydyralin! Similar to #826, I also don't see anything on Google or https://github.com/typescript-eslint/typescript-eslint/blob/master/packages/eslint-plugin/ROADMAP.md for the old `number-literal-format` rule. If the ESLint community does end up creating an equivalent rule that has a nontrivial number of npm downloads, do post here and we can reopen! Until then this issue is unfortunately blocked.
