### ISSUE TITLE
Investigate: framework-specific output logs?

### ISSUE THREAD

**Issue by JoshuaKGoldberg** [typescript-eslint/tslint-to-eslint-config#992]
### 🚀 Feature Request

Splitting out of #959: users of specifically known frameworks might need to be told to use a different tool. So far that's just angular-eslint.

#### Existing Behavior

We added a README.md notice in #959 but no runtime behavior.

#### Change Proposal

Should they be emphasized extra loudly? Block CLI running unless a flag is passed? Let's discuss.

**Comment by hyperupcall** [comment]
I know this is an old issue, but I think this should be closed as a wontfix.

Angular and its custom config conversion tool appears to be a one-off (it is unique in the JavaScript ecosystem in that it tends to have its own internal/framework-specific tooling).

And, since [v16](https://github.com/angular-eslint/angular-eslint/releases/tag/v16.0.0), this conversion feature has been completely removed. I think the link to Angular docs is still helpful, but I think that's all we need, especially as this repository ages.
